sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

before_install:
    # Ansible doesn't play well with virtualenv
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce

install:
  - sudo apt-get install -y sshpass software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-add-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get update -qq
  - sudo apt-get install -y --allow-unauthenticated ansible python3.5
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
  - sudo rm /usr/bin/python3 && sudo ln -s /usr/bin/python3.5 /usr/bin/python3
  - sudo wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
  - sudo python3 /tmp/get-pip.py
  - sudo pip3 install docker-py
  - ansible --version
  - ansible-galaxy install -r tests/requirements.yml

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml
