---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Update packages
  become: yes
  apt: update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install required packages
  become: yes
  package: name={{item}} state=present
  with_items:
    - "{{ mariadb_package }}"
    - "{{ python_mysqldb_package }}"

- name: Start MariaDB
  service:
    name: "{{ mariadb_service_name }}"
    state: started

- name: Set root password
  mysql_user:
    name: 'root'
    password: "{{ root_password }}"

- name: Write .my.cnf
  template:
    src: my.cnf
    dest: ~/.my.cnf

- name: Create databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ users }}"
  when: item.no_db is undefined or item.no_db == false

- name: Create users with grant
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.name }}.*:ALL"
    host: "{{ item.host | default('localhost', true) }}"
  with_items: "{{ users }}"
  when: item.no_db is undefined or item.no_db == false

- name: Create users without grant
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host | default('localhost', true) }}"
  with_items: "{{ users }}"
  when: item.no_db is defined and item.no_db == true